### ISSUE TITLE
ssh handshake err

### ISSUE THREAD

**Issue by justinhauer** [stardata/packer-centos7-kvm-example#1]
I've tried running your example, as well as the examples in the packer templates repo:https://github.com/jakobadam/packer-qemu-templates, but if you look at https://github.com/jakobadam/packer-qemu-templates/issues/34 it appears that several people along with myself are experiencing ssl timeout errors. Do you have any recommendation to get past this?

**Comment by velenux** [comment]
hi @justinhauer 
during the development I used to replace `text` with `vnc` in the kickstart file and used a vnc client to see what was happening during the install process, in alternative you can probably use virt-viewer to connect to the VM and examine the text install, but I've never tried that method

please consider that these examples use a very old Centos 7 ISO and the install process might have been changed in the latest releases

**Comment by velenux** [comment]
I finally managed to look into this (again).

I changed `headless: false` in `headless: true` in the config file, then I ran:
`PACKER_LOG=1 packer.io build centos7-base.json`

After the ISO download, the VM starts:
```
    qemu: The VM will be run headless, without a GUI. If you want to
    qemu: view the screen of the VM, connect via VNC without a password to
    qemu: vnc://127.0.0.1:5915
```
With VNC you can check what's going on during the installation.
The project worked without any issues using the latest ISO, I'm going to update the repo with the new link.

The only thing I can think of is that you might want to increase the `ssh_wait_timeout` from 1200 to 3600.
